.\" this is mdoc file
.\" to read manpage 
.\" $ man ./bin2dec.1
.Dd $Mdocdate$
.Dt bin2dec 1
.Sh NAME
.Nm dec2bin
.Nd convert binary to decimal
.Sh SYNOPSIS
.Nm bin2de
.Ar  binary_number
.Sh EXAMPLES
.Cm $
.Nm
1010
.Dl
  10
.Dl
.Cm $
.Nm
110100111000
.Dl
  3384
.Sh AUTHOR
 Written by Muhammed Hussam

